### ISSUE TITLE
Not sure how to use it?

### ISSUE THREAD

**Issue by farcop** [chainguard-dev/rules_apko#2]
First of all thanks for your work!

I was able to apply 1st PR as a patch and build my image with apko_image().
We plan use rules_apko to build repeatable base images.

But I can't realise next things:
1. How can I generate lock-file to use it in apko_image() to persist repeatability of generated image?
2. How can I consume output image generated by apko_image() with rules_oci or something else?

**Comment by thesayyn** [comment]
It's not completely ready for people to use but here's PR partially demonstrating how it works. https://github.com/chainguard-dev/rules_apko/pull/6

**Comment by farcop** [comment]
Thank you for clarification! Closing this.
