### ISSUE TITLE
What the difference between apko.lock.json and apko.resolved.json ?

### ISSUE THREAD

**Issue by farcop** [chainguard-dev/rules_apko#25]
In doc https://github.com/chainguard-dev/rules_apko/blob/main/README.md mentioned apko.lock.json
but at https://github.com/chainguard-dev/rules_apko/blob/main/MODULE.bazel#L34 mentioned apko.resolved.json

I suppose it needs to be cleared up.

**Comment by iDiogenes** [comment]
@farcop - I believe the documentation just needs to be updated. If you run `apko resolve /path/apko.yaml` as stated in the docs, it generates an `apko.resolved.json` file, which is what is used in the bazel rule.
