### ISSUE TITLE
Create New Release Leveraging Improvements in `apko_image`

### ISSUE THREAD

**Issue by aj185259** [chainguard-dev/rules_apko#49]
Hi all, I'd love to use the improvements to the `apko_image` rule, namely the `.lock` targets generated by [this addition](https://github.com/chainguard-dev/rules_apko/blob/main/apko/private/apko_image.bzl#L152). I'm using the `1.2.1` release as a `bazel_dep` and unfortunately, it doesn't contain those features. 

Would it be possible to cut a new release in the short term? 

Thanks!

**Comment by thesayyn** [comment]
https://github.com/chainguard-dev/rules_apko/releases/tag/v1.2.2 is out
